/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.awt.Color;
import java.awt.Rectangle;

import edu.princeton.cs.algs4.Draw;

public class App {

    private Draw desenho;

    public App(){
        this.desenho = new Draw();
        this.desenho.setXscale(0 , 600);
        this.desenho.setYscale(0 , 600);
        this.desenho.enableDoubleBuffering();
        this.desenho.setDefaultCloseOperation(3);
    }

    public void desenharQuadrado(int x, int y, int dimensao){

        desenho.setPenColor(Color.RED);
        desenho.filledSquare(x, y, dimensao);
    }

    public void desenharCirculo(int x, int y, int raio){
        desenho.setPenColor(Color.BLUE);
        desenho.filledCircle(x, y, raio);
    }



    public static void main(String[] args) {

        App  app = new App();

        int x = 300;
        int y = 300;
        int raio = 10;
        int vx = 1;
        int vy = 2;

        while(true){
            app.desenharQuadrado(400, 400, 20);
            app.desenharCirculo(x ,y, raio);   

            x+=vx;
            y+=vy;

            if((x+raio > 600) || (x+raio < 0)){
                vx *= -1;
            }
            if((y+raio > 600) || (y+raio < 0)){
                vy *= -1;
            }

            
            
            app.desenho.pause(20);
            app.desenho.show();
            app.desenho.clear(Color.WHITE);

            Rectangle r = new Rectangle(300-20,300-20,40,40);
            Rectangle outro = new Rectangle(x-raio,y-raio,2*raio,2*raio);

            if(r.intersects(outro)){
                System.out.println("Sim, bateram");
                
            }

        }


        // Robo r = new Robo(new Mapa(0, 10, 5), 5, 5, 1, 2, 5);

        // r.movimentar(1);
        // r.cavar();
    }
}
